on:
  push

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
      - uses: builtbyadam/changelog-from-commits@v1.0.0
        with:
          from-ref: ""
          to-ref: HEAD
          output-file: CHANGELOG.md
          open-pr: "false"
